on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

name: test-coverage

jobs:
  test-coverage:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: Install System Dependencies [Linux]
        if: runner.os == 'Linux'
        run: |
          Rscript -e "install.packages(c('remotes'))"

          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')

          echo "renv_dir=~/.local/share/renv" >> $GITHUB_ENV

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ${{ env.renv_dir }}
          key: ${{ matrix.config.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ matrix.config.os }}-renv-${{ hashFiles('**/renv.lock') }}-

      - name: Restore renv
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
          renv::install("covr")
        shell: Rscript {0}

      - name: Session Info
        run: |
          renv::install("sessioninfo")
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Test package coverage
        run: covr::package_coverage()
        shell: Rscript {0}
